image: golang:1.11

stages:
  - build
  - test

build:
  stage: build
  script:
    - go build ./...
    - go build -tags flatfile ./...

test:
  stage: test
  script:
    - test -z "$(gofmt -l . | tee /dev/stderr)"
    - go test ./...
    - go test -tags flatfile ./...
