image: golang:1.11

stages:
  - build
  - test

before_script:
  - go get github.com/boltdb/bolt
  - go get github.com/daaku/go.zipexe
  - go get github.com/gorilla/securecookie
  - go get github.com/kardianos/osext
  - go get golang.org/x/crypto/bcrypt

build:
  stage: build
  script:
    - go build ./...

test:
  stage: test
  script:
    - test -z "$(gofmt -l . | tee /dev/stderr)"
    - go test -cover ./...
